"""add budget fields to jobs

Revision ID: cb80a8f3b684
Revises: eb3716b8c169
Create Date: 2026-04-07 15:33:48.627304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb80a8f3b684'
down_revision: Union[str, Sequence[str], None] = 'eb3716b8c169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_insights_user_id'), table_name='user_insights')
    op.drop_table('user_insights')
    op.add_column('jobs', sa.Column('budget_min', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('budget_max', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'budget_max')
    op.drop_column('jobs', 'budget_min')
    op.create_table('user_insights',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('home_suburb', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('home_state', sa.VARCHAR(length=10), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('home_postcode', sa.VARCHAR(length=10), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('mentioned_problems', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('mentioned_assets', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('trade_interests', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('unresolved_issues', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('key_tags', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('user_intent', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('last_sentiment', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_insights_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_insights_pkey'))
    )
    op.create_index(op.f('idx_user_insights_user_id'), 'user_insights', ['user_id'], unique=True)
    # ### end Alembic commands ###
