"""initial

Revision ID: 60bd53fb203b
Revises: 
Create Date: 2026-03-19 21:52:07.946329

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '60bd53fb203b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
