"""generative_ui_columns

Revision ID: 9c44ebf16cec
Revises: 7145c88123ca
Create Date: 2026-04-04 19:04:05.708925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c44ebf16cec'
down_revision: Union[str, Sequence[str], None] = '7145c88123ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('ui_component', sa.Text(), nullable=True))
    op.add_column('chat_conversations', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('chat_conversations', sa.Column('insight_tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'insight_tags')
    op.drop_column('chat_conversations', 'image_url')
    op.drop_column('chat_conversations', 'ui_component')
    # ### end Alembic commands ###
