"""create home_assets table

Revision ID: c8df2a72b7a6
Revises: d4e5f6a7b8c9
Create Date: 2026-03-28 21:29:53.080520

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8df2a72b7a6'
down_revision: str | Sequence[str] | None = 'd4e5f6a7b8c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('homeowner_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('tradie_name', sa.String(length=200), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('expected_lifespan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homeowner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_assets_homeowner_id'), 'home_assets', ['homeowner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_assets_homeowner_id'), table_name='home_assets')
    op.drop_table('home_assets')
    # ### end Alembic commands ###
