"""add_missing_models

Revision ID: e2ea49515ac1
Revises: 17cbfd1d5b23
Create Date: 2026-03-31 21:01:12.459824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ea49515ac1'
down_revision: Union[str, Sequence[str], None] = '17cbfd1d5b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tradie_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('tax_buffer', sa.Float(), nullable=False),
    sa.Column('net_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tradie_id'], ['tradie_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_records_job_id'), 'earnings_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_earnings_records_month'), 'earnings_records', ['month'], unique=False)
    op.create_index(op.f('ix_earnings_records_tradie_id'), 'earnings_records', ['tradie_id'], unique=False)
    op.create_index(op.f('ix_earnings_records_year'), 'earnings_records', ['year'], unique=False)
    op.create_table('swms_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tradie_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tradie_id'], ['tradie_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swms_documents_tradie_id'), 'swms_documents', ['tradie_id'], unique=False)
    op.create_table('tradie_pass',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tradie_id', sa.String(), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('abn_verified', sa.Boolean(), nullable=False),
    sa.Column('abn_name', sa.String(length=200), nullable=True),
    sa.Column('abn_status', sa.String(length=50), nullable=True),
    sa.Column('abn_verified_at', sa.DateTime(), nullable=True),
    sa.Column('licence_number', sa.String(length=100), nullable=True),
    sa.Column('licence_type', sa.String(length=100), nullable=True),
    sa.Column('licence_state', sa.String(length=10), nullable=True),
    sa.Column('licence_expiry', sa.Date(), nullable=True),
    sa.Column('licence_doc_url', sa.String(length=500), nullable=True),
    sa.Column('licence_verified', sa.Boolean(), nullable=False),
    sa.Column('pli_insurer', sa.String(length=200), nullable=True),
    sa.Column('pli_amount_m', sa.Float(), nullable=True),
    sa.Column('pli_expiry', sa.Date(), nullable=True),
    sa.Column('pli_doc_url', sa.String(length=500), nullable=True),
    sa.Column('pli_verified', sa.Boolean(), nullable=False),
    sa.Column('wc_insurer', sa.String(length=200), nullable=True),
    sa.Column('wc_expiry', sa.Date(), nullable=True),
    sa.Column('wc_doc_url', sa.String(length=500), nullable=True),
    sa.Column('wc_verified', sa.Boolean(), nullable=False),
    sa.Column('white_card_number', sa.String(length=100), nullable=True),
    sa.Column('white_card_verified', sa.Boolean(), nullable=False),
    sa.Column('swms_uploaded', sa.Boolean(), nullable=False),
    sa.Column('swms_doc_url', sa.String(length=500), nullable=True),
    sa.Column('swms_updated_at', sa.DateTime(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('badge_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tradie_id'], ['tradie_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradie_pass_tradie_id'), 'tradie_pass', ['tradie_id'], unique=True)
    op.create_table('tradie_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tradie_id', sa.String(), nullable=False),
    sa.Column('accept_high_intent', sa.Boolean(), nullable=False),
    sa.Column('accept_planning', sa.Boolean(), nullable=False),
    sa.Column('notify_new_lead', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('accept_residential', sa.Boolean(), nullable=False),
    sa.Column('accept_commercial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tradie_id'], ['tradie_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradie_preferences_tradie_id'), 'tradie_preferences', ['tradie_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradie_preferences_tradie_id'), table_name='tradie_preferences')
    op.drop_table('tradie_preferences')
    op.drop_index(op.f('ix_tradie_pass_tradie_id'), table_name='tradie_pass')
    op.drop_table('tradie_pass')
    op.drop_index(op.f('ix_swms_documents_tradie_id'), table_name='swms_documents')
    op.drop_table('swms_documents')
    op.drop_index(op.f('ix_earnings_records_year'), table_name='earnings_records')
    op.drop_index(op.f('ix_earnings_records_tradie_id'), table_name='earnings_records')
    op.drop_index(op.f('ix_earnings_records_month'), table_name='earnings_records')
    op.drop_index(op.f('ix_earnings_records_job_id'), table_name='earnings_records')
    op.drop_table('earnings_records')
    # ### end Alembic commands ###
