"""update role to string

Revision ID: fedce2192243
Revises: 56013377c568
Create Date: 2026-03-19 22:31:45.981165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fedce2192243'
down_revision: Union[str, Sequence[str], None] = '56013377c568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('HOMEOWNER', 'TRADIE', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('HOMEOWNER', 'TRADIE', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
