export const TRADIE_CATEGORIES = [
  'Air Conditioning',
  'Antenna Services',
  'Appliance Installation',
  'Appliance Repairs',
  'Arborist',
  'Architecture',
  'Asbestos Removal',
  'Asphalt',
  'Attic Access Ladders',
  'Awning Suppliers',
  'Awnings',
  'Balustrading',
  'Bamboo Flooring',
  'Bath & Basin Resurfacing',
  'Bathroom',
  'Bathroom Accessories',
  'Bathroom Fittings',
  'Bathroom Sinks',
  'Bathroom Vanities',
  'Baths',
  'Beds',
  'Blinds',
  'Blinds Suppliers',
  'Building',
  'Building Certifiers',
  'Building Consultants',
  'Building Designer',
  'Building Supplies',
  'Building Surveyors',
  'Cabinet Doors',
  'Cabinet Hardware',
  'Cabinet Making',
  'Carpenters',
  'Carpet & Upholstery Cleaning',
  'Carpet Repair & Laying',
  'Carpet Suppliers',
  'Carports',
  'Ceilings',
  'Chairs',
  'Chimney Sweepers',
  'Cladding',
  'Cleaning',
  'Cleaning Products',
  'Cleaning Services - Commercial',
  'Clothesline',
  'Coffee Tables',
  'Concrete Kerbs',
  'Concrete Protection Materials',
  'Concrete Resurfacing',
  'Concrete Waterproofing Materials',
  'Concreting',
  'Cubby Houses',
  'Curtains',
  'Damp Proofing',
  'Decking',
  'Decking Oil',
  'Demolition',
  'Dining Tables',
  'Door Handles',
  'Door Hardware',
  'Door Suppliers',
  'Doors',
  'Drafting',
  'Drains',
  'Ducted Vacuum Systems',
  'Electricians',
  'Engineering - Structural',
  'Equipment Hire',
  'Excavation',
  'Extensions & Additions',
  'Fencing',
  'Fencing Materials',
  'Fencing Suppliers',
  'Feng Shui',
  'Fire Protection Materials',
  'Fireplaces',
  'Floor Coatings',
  'Floor Sanding & Polishing',
  'Flyscreens',
  'Frames & Trusses',
  'Furniture - Custom Design',
  'Furniture - Outdoor',
  'Furniture - Retailers',
  'Furniture - Second Hand',
  'Furniture Removal',
  'Garages',
  'Garden Designer',
  'Garden Features',
  'Garden Maintenance',
  'Garden Ornaments',
  'Garden Sculpture',
  'Garden Statues',
  'Garden Supplies',
  'Gas Fitters',
  'Gates',
  'Gazebo',
  'Glass & Glazing',
  'Glass Balustrades',
  'Glass Suppliers',
  'Grates',
  'Gutter Cleaning',
  'Gutter Suppliers',
  'Guttering',
  'Handles',
  'Handrail Suppliers',
  'Handrails',
  'Handyman',
  'Hardware',
  'Heaters',
  'Heating Systems',
  'Home Automation',
  'Home Theatre',
  'Homewares',
  'Hot Water Systems',
  'IKEA Bathrooms',
  'IKEA Kitchen Installers',
  'IKEA Kitchen Planners',
  'IKEA Lighting Installation and Assembly',
  'Inspections - Building',
  'Inspections - Pest',
  'Insulation',
  'Interior Decorating',
  'Interior Designer',
  'Irrigation Systems',
  'Joinery',
  'Kit Homes',
  'Kitchen',
  'Kitchen Appliances',
  'Kitchen Design',
  'Kitchen Fittings',
  'Kitchen Sinks',
  'Landscape Architecture',
  'Landscaping & Gardening',
  'Lawn & Turf',
  'Lawn Mowing',
  'Lifts',
  'Lighting',
  'Lighting Suppliers',
  'Limestone',
  'Locks',
  'Locksmiths',
  'Louvre Roofs',
  'Mailboxes',
  'Marble Stone',
  'Mirrors',
  'Mouldings',
  'Natural Stone',
  'Nurseries',
  'Paint Suppliers',
  'Painters',
  'Patios',
  'Paving',
  'Paving Supply',
  'Pergolas',
  'Pest Control',
  'Pest Control Products',
  'Pipes',
  'Plastering & Gyprock',
  'Playground Equipment',
  'Plumbers',
  'Plunge Pools',
  'Polishes',
  'Pool Accessories',
  'Pool Builders',
  'Pool Covers',
  'Pool Fencing',
  'Pool Heating',
  'Pool Maintenance',
  'Pool Suppliers',
  'Pots and Planters',
  'Pressure Cleaning',
  'Privacy Screens',
  'Professional Organisers',
  'Project Management',
  'Rainwater Tanks',
  'Render',
  'Rendering',
  'Reproduction Stone',
  'Retaining Wall Suppliers',
  'Retaining Walls',
  'Retractable Screen Suppliers',
  'Roller Doors',
  'Roller Shutters',
  'Roof Materials',
  'Roof Repairs',
  'Roofing',
  'Rubbish Removal',
  'Rugs',
  'Saunas',
  'Scaffolding',
  'Screen Enclosures',
  'Security',
  'Security Screens & Doors',
  'Shades & Sails',
  'Sheds',
  'Shelves',
  'Shopfitters',
  'Shower Screens',
  'Skip & Truck Hire',
  'Skylights',
  'Solar Power',
  'Solar Power Accessories',
  'Spas',
  'Splashback Suppliers',
  'Splashbacks',
  'Stained Glass',
  'Staircases',
  'Stone Veneer',
  'Stonemasonry',
  'Storage',
  'Surveyors',
  'Tile Suppliers',
  'Tilers',
  'Toilet Suppliers',
  'Tools',
  'Town Planning',
  'Tree Felling',
  'TV Units',
  'Underfloor Heating',
  'Underpinning',
  'Upholstery Repair',
  'Vacuum Cleaners',
  'Ventilation',
  'Verandahs',
  'Vinyl & Laminate',
  'Wallpapering',
  'Wardrobe Suppliers',
  'Wardrobes',
  'Water Features',
  'Water Filtration Systems',
  'Water Pumps',
  'Waterproofing',
  'Waterproofing Products',
  'Window Cleaning',
  'Window Repairs',
  'Window Shutters',
  'Window Tinting',
  'Windows',
  'Wine Racks',
  'Wood Care Products'
];
