version: "3.9"

services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: ProConnect_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ProConnect_dev
      POSTGRES_USER: hipages
      POSTGRES_PASSWORD: devpassword
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ProConnect_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
